{{- $imageE2ETestEngine := .Values.imageAutonityE2ETestEngine -}}
{{- $namespace := .Release.Namespace -}}
{{- $validatorIps :=  .Values.validators.ips -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2eTestEngine
  namespace: {{ $namespace }}
spec:
  selector:
    matchLabels:
      app: e2eTestEngine
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: e2eTestEngine
    spec:
      containers:
        - name: e2eTestEngine
          image: {{ $imageE2ETestEngine.repository }}:{{ $imageE2ETestEngine.tag }}
          env:
          {{- if $validatorIps }}
          - name: VALIDATOR_IPS
            value: "{{ range $i, $e := until (atoi (printf "%d" (int64 .Values.validators.num))) }}{{index $validatorIps $i }} {{ end }}"
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
          lifecycle:
            postStart:
              exec:
                command: ["python3", "e2etestengine.py", "./bin/autonity", "-b", "true"]
