{{- $namespace := .Release.Namespace -}}

{{- $serviceType :=  .Values.validators.serviceType -}}
{{- $ips :=  .Values.validators.ips -}}


{{ range $i, $e := until (atoi (toString .Values.validators.num)) }}
---
apiVersion: v1
kind: Service
metadata:
  name: validator-{{ $i }}
  namespace: {{ $namespace }}
spec:
  type: {{ $serviceType }}
  {{ if eq $serviceType "LoadBalancer" }}
  loadBalancerIP: {{index $ips $i }}
  loadBalancerSourceRanges:
  {{- range $ips }}
  - {{ . }}/32
  {{- end }}
  {{- end }}
  ports:
    - protocol: TCP
      name: http-rpc
      port: 6000
      targetPort: 6000
    - protocol: TCP
      name: wss
      port: 7000
      targetPort: 7000
    - protocol: TCP
      name: p2p
      port: 30303
      targetPort:  30303
  selector:
    app: validator-{{ $i }}
  {{- end}}