---
imageClientUbuntuHost:
  repository: ironmanjason/client_host
  tag: 0.0.1

imageAutonityE2ETestEngine:
  repository: ironmanjason/test_engine
  tag: 0.0.7

# Number of validators
validators:
  num: 6
  serviceType: "ClusterIP"

e2e_test_engine:
  serviceType: "ClusterIP"
